log4j.logger.org.apache.kafka=WARN, stdout
log4j.logger.com.lightstreamer.kafka.examples.airport.producer.Producer=INFO, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d] [%c{1}] %-5p %m%n
log4j.appender.stdout.Target=System.out
 
