[versions]
com-fasterxml-jackson-core-jackson-annotations = "2.17.0"
io-confluent-kafka-json-serializer = "7.7.0"
org-apache-kafka-kafka-clients = "3.8.0"
org-slf4j-slf4j-reload4j = "2.0.18"

[libraries]
com-fasterxml-jackson-core-jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "com-fasterxml-jackson-core-jackson-annotations" }
io-confluent-kafka-json-serializer = { module = "io.confluent:kafka-json-serializer", version.ref = "io-confluent-kafka-json-serializer" }
org-apache-kafka-kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "org-apache-kafka-kafka-clients" }
org-slf4j-slf4j-reload4j = { module = "org.slf4j:slf4j-reload4j", version.ref = "org-slf4j-slf4j-reload4j" }
