# ClassGraph
ClassGraph=https://github.com/classgraph/classgraph/blob/latest/LICENSE-ClassGraph.txt?raw=true

# Protocol Buffers
Protocol\ Buffers\ [Core]=https://github.com/protocolbuffers/protobuf/blob/main/LICENSE?raw=true
Protocol\ Buffers\ [Util]=https://github.com/protocolbuffers/protobuf/blob/main/LICENSE?raw=true

# javapoet
javapoet=https://github.com/palantir/javapoet/blob/develop/LICENSE.txt=?raw=true

# msal4j-persistence-extension
msal4j-persistence-extension=https://raw.githubusercontent.com/palantir/javapoet/refs/heads/develop/LICENSE.txt

# msal4j
msal4j=https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/LICENSE?raw=true

# asm
asm=https://github.com/ljvblfz/asm/blob/master/LICENSE.txt?raw=true