FROM lightstreamer

ARG version

COPY deploy/lightstreamer-kafka-connector-${version}.zip /tmp/lightstreamer-kafka-connector.zip
USER root
RUN apt-get -y update; \
    apt-get install -y unzip; \
    unzip /tmp/lightstreamer-kafka-connector.zip -d /lightstreamer/adapters

USER lightstreamer