FROM lightstreamer

COPY deploy/lightstreamer-kafka-connector-*.zip /tmp/lightstreamer-kafka-connector.zip
COPY web /lightstreamer/pages/QuickStart

USER root
RUN apt-get -y update; \
    apt-get install -y unzip; \
    unzip /tmp/lightstreamer-kafka-connector.zip -d /lightstreamer/adapters

USER lightstreamer